# CircleCI configuration file
version: 2.1

jobs:
  build:
    docker:
    # Primary container image where all steps run
     - image: swaggerapi/swagger-ui
    steps:
      - run: echo "Say hello to YAML!"